version: '3.8'

services:
  backend:
    build: .
    container_name: care-service-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Только необходимые переменные
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-care_service}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres123}
      DDL_AUTO: ${DDL_AUTO:-update}
      JWT_SECRET: ${JWT_SECRET:-53A73E5F1C4E0A2D3B5F2D784E6A1B423FFF247D1F6E5C3A596D635A75327855}
      SERVER_PORT: 8080
    networks:
      - care-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: care-service-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres123}
      POSTGRES_DB: ${DB_NAME:-care_service}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - care-network

volumes:
  postgres-data:

networks:
  care-network:
    driver: bridge